version: "1.27"

services:
  verdaccio:
    image: verdaccio/verdaccio
    container_name: "verdaccio"
    network_mode: host
    networks:
      - node-network
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./storage:/verdaccio/storage"
      - "./config:/verdaccio/conf"
      - "./plugins:/verdaccio/plugins"
networks:
  node-network:
    driver: bridge
