# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Build Docker Image And Publish to Docker Hub

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*.*.*" # Match tags like antd/v1.0.0-alpha.0, antd-v5/v1.0.0-beta.0

permissions:
  contents: write
  discussions: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Parse Tag
        id: parse_tag
        run: |
          # 获取标签名称
          tag_name="${GITHUB_REF:10}"

          # 提取功能模块名称
          module_name=$(echo $tag_name | cut -d'/' -f1)

          # 提取版本号
          version=$(echo $tag_name | cut -d'/' -f2)

          tag="latest"
          pre_release=false
          # 检查是否预发布
          if [[ $tag_name == *"alpha"* ]]; then
            tag="alpha"
            pre_release=true
          fi

          if [[ $tag_name == *"beta"* ]]; then
            tag="beta"
            pre_release=true
          fi

          echo "::set-output name=pre_release::$pre_release"
          echo "::set-output name=module_name::$module_name"
          echo "::set-output name=tag_name::$tag_name"
          echo "::set-output name=version::$version"
          echo "::set-output name=tag::$tag"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            chaogpt/bunpkg:latest
            chaogpt/bunpkg:${{ steps.parse_tag.outputs.tag_name }}
